### ISSUE TITLE
Barnes and Noble book fields

### ISSUE THREAD

**Issue by N8Stewart** [N8Stewart/Book-Scraper#1]
What fields do you think we need for the book? Below are the fields I have. Let me know if you have any others that I am missing. 

String Title
String Author
String Publisher
String Edition
String ISBN
Float Price
Image Image

Should we store an array of majors, courses, and sections for which the book applies? For example, AeroEng 3851 and MechEng 2560 both require the same book (made up example). This way, we are not storing duplicate information?

**Comment by StoneSylent** [comment]
Provided in the <a href=https://github.com/nandu-khobare/OSUsed/blob/master/Documents/OSUsedArchitecture.pdf>documentation</a> the database should look like this:
![image](https://cloud.githubusercontent.com/assets/10569286/10117242/8f73c2b8-641d-11e5-8288-c9083dd302ff.png)
Using Microsoft SQL Server Management Studio I can see the database and modify it as needed. 
Here are the types for the book information:
![image](https://cloud.githubusercontent.com/assets/10569286/10117281/d62bf3a0-641e-11e5-9300-767375fc3a8b.png)
It does appear the edition and publisher of each book are not stored anyplace.

**Comment by N8Stewart** [comment]
Yea, that's why I made the post in the first place. I noticed several key fields were not in the db at all so I was looking for feedback on what else should be added. We want to get this piece done as soon as possible so as to not continuously be changing the Book.rb records every time we want to add another piece of information.

**Comment by StoneSylent** [comment]
Ok so (1) adding the database fields should be easy. The (2) search bar sql request should be a simple enough change. (3)Updating the results pages will require a little more work. (4) As will adding the books to the database manually. I will looking into 3&4 briefly, if no major issues are found I will have 1&2 ready for git in a few hours after my next class. 3&4 depending on there complexity. Lastly documentation will need updating.

**Comment by StoneSylent** [comment]
1,2,3 are complete. Modifying the *.aspx.cs file should automatically update the *aspx.cs.designer.cs file.
Exam tomorrow and class tonight so 4 will be worked on sometime around 4pm tomorrow. If everything goes well this issue will be closed before class (capstone) tomorrow.

**Comment by StoneSylent** [comment]
Closing issue as database is being redone to fix some issues. Book prices, etc. Monday oct 19th meeting should help clearly database changes.
