### ISSUE TITLE
Develop Upload Script

### ISSUE THREAD

**Issue by N8Stewart** [N8Stewart/Book-Scraper#4]
Take all books stored locally and upload into the OSUsed site database.

**Comment by N8Stewart** [comment]
This needs some research. Initial assumption is to use SQL*Loader or Ruby capybara to upload. Assume you have an array of book structures. Need to check if the book exists. If it doesn't, upload.

**Comment by StoneSylent** [comment]
Hint: ![img_0844](https://cloud.githubusercontent.com/assets/10569286/10708871/c178656e-79e6-11e5-8d97-922c9d62252b.JPG)
